name: Test

on:
  workflow_dispatch:

jobs:
  build-and-compile:
    runs-on: windows-latest
    steps:
      - name: Disk Space Optimizer
        uses: hugoalh/disk-space-optimizer-ghaction@v0.8.1
        with:
          general_include: ".+"
          docker_exclude: /mcr.microsoft.com\/windows\/servercore:ltsc2022/gm
          docker_include: ".+"
          docker_prune: "True"
          docker_clean: "True"
          apt_prune: "True"
          apt_clean: "True"
          homebrew_prune: "True"
          homebrew_clean: "True"
          npm_prune: "True"
          npm_clean: "True"
          os_swap: "True"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone rustdesk
        run: |
          git clone https://github.com/rustdesk/rustdesk.git

      - name: Build image
        run: |
          cd Windows-x64
          ./build

      - name: Compile
        run: |
          cd Windows-x64
          ./compile
