name: Test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone rustdesk
        run: |
          git clone https://github.com/rustdesk/rustdesk.git
        
      - name: Compile1
        shell: powershell
        run: |
          cd Windows-x64
          ls

      - name: Compile2
        shell: powershell
        run: |
          cd Windows-x64
          ls