name: Test

on:
  workflow_dispatch:

jobs:
  build-and-compile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone rustdesk
        run: |
          git clone https://github.com/rustdesk/rustdesk.git

      - name: Build image
        run: |
          cd Windows-x64
          ./build

      - name: Compile
        run: |
          cd Windows-x64
          ./compile
