name: Test

on:
  workflow_dispatch:

jobs:
  build-and-compile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone rustdesk
        run: git clone --single-branch --branch 5c16a8302e6c9c1381873aff45dba1487ee51d4f https://github.com/rustdesk/rustdesk.git

      - name: Build docker images
        run: |
          cd Windows-x64
          ./build

      - name: Compile
        run: |
          cd Windows-x64
          ./compile
